services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/ernurator/nfactorial-incubator-backend-hw-2023.git
    region: frankfurt
    branch: main
    envVars:
      - key: MONGO_URL
        sync: false
    buildFilter:
      paths:
      - app/**
